### ISSUE TITLE
16주차 자바 메모리 모델

### ISSUE THREAD

**Issue by SooJungDev** [SooJungDev/study-java-concurrency-in-practice#16]
## 16주차 자바 메모리 모델
16.1 자바 메모리 모델은 무엇이며, 왜 사용해야 하는가
16.2 안전한 공개
16.3 초기화 안전성

## 마지막 회차 스터디 회고 ^__________^

**Comment by great0417** [comment]
[끝](https://github.com/great0417/java_parallel/blob/main/16%EC%9E%A5.md)

**Comment by SooJungDev** [comment]
[끝!](https://github.com/SooJungDev/TIL/blob/master/Java/%EC%9E%90%EB%B0%94%20%EB%B3%91%EB%A0%AC%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D%20%EC%8A%A4%ED%84%B0%EB%94%94/16.16%EC%9E%A5%20%EC%9E%90%EB%B0%94%20%EB%A9%94%EB%AA%A8%EB%A6%AC%20%EB%AA%A8%EB%8D%B8.md)

**Comment by garlickim** [comment]
[16주차 과제](https://github.com/garlickim/study-note/blob/main/book/java-concurrency-in-practice/%5Bweek16%5D%20%EC%9E%90%EB%B0%94%20%EB%A9%94%EB%AA%A8%EB%A6%AC%20%EB%AA%A8%EB%8D%B8.md)
